name: Docker Images CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: "${{ secrets.UNAME }}"
        password: "${{ secrets.PASS }}"
        
    # - name: Decode and add .env file for frontend
    #   run: echo "${{ secrets.ENV_F }}" | base64 -d > frontend/.env

    - name: Decode and add .env file for backend
      run: echo "${{ secrets.ENV }}" | base64 -d > backend/.env
    - name: Decode and add service account keys for backend
      run: echo "${{ secrets.FIREBASE }}" | base64 -d > backend/src/firebase/serviceAccountKeys.json

    - name: Build and push backend Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --file ./backend/Dockerfile \
          --tag cruxsphere/survey-b:latest \
          --tag cruxsphere/survey-b:$(date +%s) \
          ./backend \
          --push


    - name: Build and push frontend Docker image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --file ./frontend/Dockerfile \
          --tag cruxsphere/survey-f:latest \
          --tag cruxsphere/survey-f:$(date +%s) \
          ./frontend \
          --push
